More v1.4 Bug Fixes
AY2122S1-CS2103T-T10-1/tp pull request #224
Opened 2021-11-02 07:14 UTC by crypto-code

2021-11-02 15:26 UTC, CheongYeeMing approved these changes
Well written code! Test cases updated when resolving issues from PE-D. 😄

2021-11-02 15:26 UTC, CheongYeeMing commented on src/main/java/seedu/address/logic/parser/ShowCommandParser.java
> +        }
Good use of defensive programming! 👍

2021-11-03 04:15 UTC, CheongYeeMing approved these changes
Many issues were resolved. Just some minor changes to be done! 👍

2021-11-03 04:15 UTC, CheongYeeMing commented on src/main/java/seedu/address/commons/util/StringUtil.java
> +     */
Hi, do leave an empty line between the description and the `@throws` as part of our standardisation of Javadocs format. 😄

2021-11-03 04:15 UTC, CheongYeeMing commented on src/main/java/seedu/address/commons/util/StringUtil.java
>      }
It will be better to set `\\s+` as a variable as it is repeated a few times. (Take a look at `containsWordIgnoreCase` method above).

2021-11-03 04:15 UTC, CheongYeeMing commented on src/main/java/seedu/address/logic/commands/ShowCommand.java
> +            + "You can try show with index or full %2$s";
Good use of variables! 👍

2021-11-03 04:15 UTC, CheongYeeMing commented on src/main/java/seedu/address/model/person/Person.java
> +                || otherPerson.getGithub().equals(getGithub());
Resolves the issue for "duplicate" contacts! 👍

2021-11-03 04:15 UTC, CheongYeeMing commented on src/main/java/seedu/address/model/tag/Tag.java
> +        return types[type.ordinal()];
Similar issue. `"event-"` and `"mod-"` repeated below in `parseTagType`. Better to set as variables. 😄

2021-11-03 04:23 UTC, moreTriangles requested changes
Great work, just minor formatting issues

2021-11-03 04:23 UTC, moreTriangles commented on src/main/java/seedu/address/logic/commands/ShowCommand.java
>          if (filteredList.isEmpty()) {
Deep nesting, arrowhead style code. Possible to abstract further?

2021-11-03 04:23 UTC, moreTriangles commented on src/main/java/seedu/address/logic/commands/ShowCommand.java
>              } else {
`else` here can be omitted to reduce nesting

2021-11-03 04:23 UTC, moreTriangles commented on src/main/java/seedu/address/logic/parser/AddressBookParser.java
> +
Neat way to handle all single words commands

2021-11-03 04:58 UTC, moreTriangles approved these changes
LGTM 👍

2021-11-03 04:59 UTC, merged